### ISSUE TITLE
Is there any way to generate Client ID and Client Secret using rest api for google auto-ml ?

### ISSUE THREAD

**Issue by Ankitappperfect** [googleapis/java-automl#121]
I'm able to authenticate the user using client id and client secret(taking from GCP console). But is there any way to generate client id and secret using REST APIs or Java SDK by taking user-id and password as an input parameter?

**Comment by nnegrey** [comment]
Howdy, typically we recommend using Service Accounts when using the client libraries but that can depend on your use case. 
Here's an overview of Authentication on GCP: https://cloud.google.com/docs/authentication
