### ISSUE TITLE
AutoML prediction bug on java

### ISSUE THREAD

**Issue by zafark0695** [googleapis/java-automl#13]
I used the java code to perform translation prediction on my custom model on google cloud.
This the java code on google cloud [docs](https://cloud.google.com/translate/automl/docs/tutorial#tutorial-translate-predict-java)

This is my modified code, because on the docs the java code async, so i modified it to make it like so. and added a toast for it to display the translation back. However the toast is returning blank. Any one can help me fix it. It seems to crash on this line `PredictionServiceClient predictionClient = PredictionServiceClient.create();` what ever i try to it fails to execute a predictionServiceClient create.
 I tried the following:

1) [Manipulating with the create](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/PredictionServiceClient.java)

2) Put it in a try catch block and that is where i found out that the create line is where it is failing

3) Tried on emulator and on tablet still no dice. 

#### Environment details
API = Google Cloud AutoML translation
OS = Windows 10 version 1809
Java version= Version 8 update 201

#### Code example

```package com.example.translation;

import android.annotation.SuppressLint;
import android.os.AsyncTask;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.Toast;

import com.google.cloud.automl.v1beta1.ExamplePayload;
import com.google.cloud.automl.v1beta1.ModelName;
import com.google.cloud.automl.v1beta1.PredictResponse;
import com.google.cloud.automl.v1beta1.PredictionServiceClient;
import com.google.cloud.automl.v1beta1.TextSnippet;
import java.util.HashMap;
import java.util.Map;

public class Main2Activity extends AppCompatActivity {
    String finalResult="";
    String projectId = "gtranslate-1234567";
    String computeRegion = "us-central1";
    String modelId = "TRL--------------------------";
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);

      getData();

    }
    public void predict(String finalResult)
    {
        Toast.makeText(getBaseContext(),finalResult, Toast.LENGTH_LONG).show();
    }

    public void getData(){

        @SuppressLint("StaticFieldLeak")
        class GetDataJSON extends AsyncTask<String, Void, String> {

            @Override
            protected String doInBackground(String... params) {

                String result = "";
                try {
                    PredictionServiceClient predictionClient = PredictionServiceClient.create();

                    // Get the full path of the model.
                    ModelName name = ModelName.of(projectId, computeRegion, modelId);

                    // Read the file content for translation.
                    String content = "Hello World.";

                    TextSnippet textSnippet = TextSnippet.newBuilder().setContent(content).build();

                    // Set the payload by giving the content of the file.
                    ExamplePayload payload = ExamplePayload.newBuilder().setTextSnippet(textSnippet).build();

                    // Additional parameters that can be provided for prediction
                    Map<String, String> params1 = new HashMap<>();

                    PredictResponse response = predictionClient.predict(name, payload, params1);
                    TextSnippet translatedContent = response.getPayload(0).getTranslation().getTranslatedContent();
                    result = String.format("Translated Content: %s", translatedContent.getContent());
                    Toast.makeText(getBaseContext(),String.format("Translated Content: %s", translatedContent.getContent()), Toast.LENGTH_LONG).show();
                } catch (Exception e) {
                    // Oops
                }
                return result;
            }

            @Override
            protected void onPostExecute(String result){
                finalResult=result;
                predict(result);
                predict(finalResult);
            }
        }
        GetDataJSON g = new GetDataJSON();
        g.execute();
    }

}
```
On Python and Node JS it is working fine after making the code async. However, on java the toast returns blank.
I added my credentials to android studio terminal like so "set GOOGLE_APPLICATION_CREDENTIALS= path/to/my/json/file.json

Thanks!

**Comment by nnegrey** [comment]
This is for Android? 
Our libraries don't necessarily work on Android without doing some additional work in the build.gradle. 

You may not want to store credentials directly on the device, you'll want to create a tokens service.
This tutorial shows how to call the token service from iOS, but the same principles apply to Android, you'll just have to check the Firebase Functions docs for how to call the Function from Android.
https://cloud.google.com/solutions/mobile/token-service-oauth
