### ISSUE TITLE
Get INVALID_ARGUMENT Response on PredictRequest

### ISSUE THREAD

**Issue by tausendschoen** [googleapis/java-automl#528]
Hello, 
I use one of the examples to send a predict request to AutoML backend. But I receive an INVALID_ARGUMENT Excpeption. But I have no glue where the source of the error is. I did not change the example code. My be it is outdated.

> try (PredictionServiceClient client = PredictionServiceClient.create()) {
> 
>             TextSnippet textSnippet = TextSnippet.newBuilder()
>                             .setContent(content)
>                             .setMimeType("text/plain") // Types: text/plain, text/html
>                             .build();
> 
>             // Get the full path of the model.
>             ModelName name = ModelName.of(projectId, location, modelId);
>             ExamplePayload payload = ExamplePayload.newBuilder().setTextSnippet(textSnippet).build();
>             PredictRequest predictRequest = PredictRequest.newBuilder()
>                     .setName(name.toString())
>                     .setPayload(payload)
>                     .build();
> 
> 
>             PredictResponse response = client.predict(predictRequest);
> 
>             for (AnnotationPayload annotationPayload : response.getPayloadList()) {
>                 System.out.format("Predicted class name: %s\n", annotationPayload.getDisplayName());
>                 System.out.format(
>                         "Predicted class score: %.2f\n", annotationPayload.getClassification().getScore());
>             }
>         } 

The resulting exception is:

> Status Code: GrpcStatusCode{transportCode=INVALID_ARGUMENT}
> Message : io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Request contains an invalid argument.
> com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Request contains an invalid argument.
> 	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:49)
> 	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
> 	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
> 	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
> 	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
> 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1041)
> 	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
> 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1215)
> 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:983)
> 	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:771)
> 	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:563)
> 	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
> 	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:464)
> 	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:428)
> 	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:461)
> 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
> 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
> 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
> 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
> 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
> 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
> 		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
> 		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
> 		at com.google.cloud.automl.v1beta1.PredictionServiceClient.predict(PredictionServiceClient.java:335)
> 		at com.mc.image.AutoMlClient.predict(AutoMlClient.java:44)
> 		at com.mc.image.AutoMlClient.main(AutoMlClient.java:17)
> Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Request contains an invalid argument.
> 	at io.grpc.Status.asRuntimeException(Status.java:535)

Furthermore I can the the error within the google cloude API Dashboard. But I am not able to detect the error. 
The model itself is working fine (tested with the google console)

Any ideas how to solf the problem? Any better implementations or samples available?

Best regards
Michael

**Comment by munkhuushmgl** [comment]
@tausendschoen Could you tell which AUtoML product ? example : language [text classification, entity extraction, sent analysis] or Vision or Translate?

**Comment by tausendschoen** [comment]
I found the bug. I mistook the dataset ID and the model ID.
