### ISSUE TITLE
Java libraries do not work in Android due to GRPC version compatibility issues

### ISSUE THREAD

**Issue by shivangsgangadia** [googleapis/java-automl#79]
I need to call AutoML tables via an Android app for live predictions. I tried using the client library, but when I sync the build.gradle in Android Studio, I get the following error:
```
ERROR: In project 'app' a resolved Google Play services library dependency depends on another at
an exact version (e.g. "[1.21.0]", but isn't being resolved to that version. Behavior exhibited by the
library will be unknown.
Dependency failing: io.grpc:grpc-okhttp:1.21.0 -> io.grpc:grpc-core@[1.21.0], but grpc-core
version was 1.25.0.
```

I do not know if I can change the GRPC version or that if it is a good idea. A probable solution is to use the REST API, but it gets cumbersome due to expiring access tokens. Is there a way I can get around this ?

**Comment by elharo** [comment]
Import libraries-bom: https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM
